#!/usr/bin/env bash
# made by Luca Guzzi ft. AI

parall () {
    local msg() {
        printf '%b %s\n' "$1" "$2"
    }
    local info() {
        msg "\e[0;32mparall.info\e[0m" "$1"
    }
    local error() {
        msg "\e[0;31mparall.error\e[0m" "$1" >&2
    }
    local warning() {
        msg "\e[0;33mparall.warning\e[0m" "$1"
    }
    if ! command -v xargs >/dev/null 2>&1; then
        error "xargs is not installed and is required for parall"
        return 1
    fi
    local jobs=1
    local command=""
    local verbose=0
    local -a iterables=()
    while [ "$#" -gt 0 ]; do
        case "$1" in
            -h) 
                printf "parall - Run commands in parallel using xargs\\n"
                printf "Usage: parall [-j N] [-v] [-c command] [-i iterable1 iterable2 ...]\\n"
                printf "  -j N        Number of jobs to run in parallel (default: 1)\\n"
                printf "  -v          Enable verbose output (default: off)\\n"
                printf "  -c command  Command to run for each iterable (required)\\n"
                printf "  -i iterable1 iterable2 ...  List of iterables to process (required)\\n"
                return 0
                ;;
            -j)
                [ "$#" -ge 2 ] || {
                    error "Missing value for -j"
                    return 1
                }
                jobs=$2
                shift 2
                ;;
            -j?*)
                jobs=${1#-j}
                shift
                ;;
            -v)
                verbose=1
                shift
                ;;
            -c)
                [ "$#" -ge 2 ] || {
                    error "Missing value for -c"
                    return 1
                }
                local command_string=$2
                shift 2
                ;;
            -i)
                [ "$#" -ge 2 ] || {
                    error "Missing value for -i"
                    return 1
                }
                shift

                while [ "$#" -gt 0 ] && [[ "$1" != -* ]]; do
                    iterables+=("$1")
                    shift
                done
                ;;
            --)
                shift
                iterables+=("$@")
                break
                ;;
            *)
                error "Unknown option: $1"
                return 1
                ;;
        esac
    done

    [ -n "$command_string" ] || {
        error "No command specified"
        return 1
    }

    ((${#iterables[@]})) || { error "No iterables specified"; return 1; }


    case "$jobs" in
        ''|*[!0-9]*|0)
            error "Jobs must be a positive integer"
            return 1
            ;;
    esac

    warning "Running command: $command_string"
    warning "Iterables: $iterables"
    [ $verbose -eq 1 ] && warning "Using $jobs jobs" || :
    warning "Proceed? (y/[n])"
    read -r answer
    if [[ ! "$answer" =~ ^[Yy]$ ]]; then
        info "Aborting"
        return 0
    fi

    printf '%s\0' "${iterables[@]}" | xargs -0 -r -n 1 -P "$jobs" bash -c "$command_string \"\$1\"" _
}
